spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keeping_maintenance
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000