spring:
  main:
    banner-mode: off
    lazy-initialization: true
  application:
    name: KeepingMaintenance
    version: 1.0.0

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 10
        order_updates: true
        cache:
          use_query_cache: false
          use_second_level_cache: false

  profiles:
    active: test

server:
  tomcat:
    threads:
      max: 20
      min-spare: 5
